services:
  mysql-container:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=order-service-database
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    volumes:
      - mysql-data-container:/var/lib/mysql
      - ./mysql-data-container/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reactive-order-service-network

  mongo-container:
    image: mongo:6.0.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - reactive-order-service-network

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo-container
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-container
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    networks:
      - reactive-order-service-network

volumes:
  mysql-data-container:
    driver: local
  mongodb_data_container:
    driver: local

networks:
  reactive-order-service-network: